name = "skify-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Run: wrangler d1 create skify-db
# Then paste the database_id below
[[d1_databases]]
binding = "DB"
database_name = "skify-db"
database_id = "1dba62c9-8052-4eb3-8e9c-696fb2f783e2"

[[r2_buckets]]
binding = "SKILLS"
bucket_name = "skify-storage"

[vars]
GITHUB_API = "https://api.github.com"
